services:
  webapp:
    extends:
      file: webapp/compose.yaml
      service: webapp
    build:
      args:
        PLATFORM: stm32mp257
        REMOTEPROC: m33
  zephyr:
    extends:
      file: zephyr-application/compose.yaml
      service: zephyr
    build:
      args:
        PLATFORM: stm32mp257
        REMOTEPROC: m33

x-topo:
  name: "hetereogenous-lightbulb-demo"
  description: "A zephyr application that reads the state of a gpio pin to determine if a switch is flipped,\nand a webapp that displays the state of the switch in real time, demonstrating Remoteproc message and \nheterogenous application deployment.\n"
  args:
    PLATFORM:
      description: The platform to build for. Must be either 'stm32mp257' or 'imx93'.
      default: stm32mp257
    REMOTEPROC:
      description: The remoteproc driver to use. Must be 'm33' if the stm32 board is used, or 'imx-rproc' if the imx93 board is used.
      default: m33
