services:
  zephyr:
    build:
      context: .
      args:
        PLATFORM: ${PLATFORM:-stm32mp257} # overridden to 'imx93' for imx93 systems
    runtime: io.containerd.remoteproc.v1
    annotations:
      remoteproc.name: ${REMOTEPROC:-m33} # overridden to 'imx-rproc' for imx93 systems
