services:
  webapp:
    build:
      context: .
    image: webapp:latest
    privileged: true
    ports:
      - "3000:3000"
    volumes:
      # We mount the entirety of dev because when this is deployed *with* the remoteproc application, the device /dev/ttyRPMSG0 doesn't exist until zephyr has fully booted, so this container would fail to build.
      - "/dev:/dev"
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
    depends_on:
      - zephyr
    restart: on-failure
