[project]
name = "stm32-a-m-comms-userapp"
version = "0.1.0"
description = "A python application that recieves state updates from a RPMSG channel and presents on a web interface."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "eventlet>=0.40.3",
    "flask>=3.1.2",
    "flask-socketio>=5.5.1",
    "python-socketio>=5.14.3",
    "ruff>=0.14.4",
]
